name: dart_profanity
description: This package censores profanity in String sequences and delivers some censor options for your needs.
version: 1.0.1
homepage: https://rahmi-tufanoglu-homepage-next.vercel.app/
repository: https://github.com/RahmiTufanoglu/dart_profanity
issue_tracker: https://github.com/RahmiTufanoglu/dart_profanity/issues
# documentation:

environment:
  sdk: '>=2.17.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
