name: dart_profanity
description: This package censores profanity in String sequences and delivers some censor options for your needs.
version: 1.0.0
homepage: https://rahmi-tufanoglu-homepage-next.vercel.app/

environment:
  sdk: '>=2.17.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
